In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [6]:
df = pd.read_csv("bruteforce.csv")

In [7]:
df.shape

(14501, 60)

In [8]:
df.head()

,frame.time_delta,frame.time_delta_displayed,frame.time_epoch,frame.time_invalid,frame.time_relative,eth.src,eth.dst,ip.src,ip.dst,tcp.srcport,...,mqtt.topic,mqtt.topic_len,mqtt.username,mqtt.username_len,mqtt.ver,mqtt.willmsg,mqtt.willmsg_len,mqtt.willtopic,mqtt.willtopic_len,ip.proto
0,0.000000,0.000000,1.592812e+09,NaN,0.000000,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,55363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
1,0.026297,0.026297,1.592812e+09,NaN,0.026297,bc:5f:f4:65:87:30,8c:85:90:b3:e6:d9,192.168.1.91,192.168.1.90,1883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
2,0.000095,0.000095,1.592812e+09,NaN,0.026392,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,55363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
3,0.000300,0.000300,1.592812e+09,NaN,0.026692,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,55363,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,6
4,0.001360,0.001360,1.592812e+09,NaN,0.028052,bc:5f:f4:65:87:30,8c:85:90:b3:e6:d9,192.168.1.91,192.168.1.90,1883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6

In [9]:
df.tail()

,frame.time_delta,frame.time_delta_displayed,frame.time_epoch,frame.time_invalid,frame.time_relative,eth.src,eth.dst,ip.src,ip.dst,tcp.srcport,...,mqtt.topic,mqtt.topic_len,mqtt.username,mqtt.username_len,mqtt.ver,mqtt.willmsg,mqtt.willmsg_len,mqtt.willtopic,mqtt.willtopic_len,ip.proto
14496,0.963651,0.963651,1.592814e+09,NaN,2237.391972,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,61562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
14497,0.001615,0.001615,1.592814e+09,NaN,2237.393587,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,61562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
14498,0.028347,0.028347,1.592814e+09,NaN,2237.421934,bc:5f:f4:65:87:30,8c:85:90:b3:e6:d9,192.168.1.91,192.168.1.90,1883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
14499,0.000284,0.000284,1.592814e+09,NaN,2237.422218,bc:5f:f4:65:87:30,8c:85:90:b3:e6:d9,192.168.1.91,192.168.1.90,1883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
14500,0.000056,0.000056,1.592814e+09,NaN,2237.422274,8c:85:90:b3:e6:d9,bc:5f:f4:65:87:30,192.168.1.90,192.168.1.91,61562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6

In [10]:
df.isnull().values.any()  #mengetahui apakah ada data yang kosong atau tidak

True

In [ ]:
def